# permissions for end users to view webpages.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: webpage-viewer-role
rules:
- apiGroups:
  - sandbox.morhidi.io
  resources:
  - webpages
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - sandbox.morhidi.io
  resources:
  - webpages/status
  verbs:
  - get
