apiVersion: v1
kind: Pod
metadata:
  name: webserver
spec:
  containers:
  - name: webserver
    image: nginx:latest
    ports:
    - containerPort: 80
    volumeMounts:
      - name: static
        mountPath: /usr/share/nginx/html
  volumes:
  - name: static
    hostPath:
      path: /tmp/static 
